# Generated by Django 4.2.4 on 2023-08-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mine',
            name='message',
        ),
        migrations.AddField(
            model_name='mine',
            name='confirm_password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='mine',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
