# Generated by Django 4.2.4 on 2023-08-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_mine_message_mine_confirm_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mine',
            new_name='signup',
        ),
    ]
