# Generated by Django 4.2.4 on 2023-08-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_mine_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
